<a href="https://colab.research.google.com/github/vaibhav12686/Hybrid-Recommender-System/blob/main/Content_Based_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kagglehub --upgrade

Requirement already satisfied: kagglehub in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2026.7.22)

In [2]:
import kagglehub

In [3]:
kagglehub.dataset_download("undefinenull/million-song-dataset-spotify-lastfm")

Downloading to /root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/1.archive...

100%|██████████| 639M/639M [00:04<00:00, 152MB/s]

Extracting files...

'/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1'

In [4]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data_path = Path("/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1")


songs_data_path = data_path / 'Music Info.csv'
users_data_path = data_path / 'User Listening History.csv'

In [6]:
from pathlib import Path

for p in data_path.rglob("*"):
    print(p)

/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/User Listening History.csv
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/Music Info.csv
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Jazz
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/RnB
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/New Age
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Electronic
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Rap
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Pop
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Rock
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Country
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Metal
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Reggae
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Punk
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Blues
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Latin
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRRRWRI128F149B8F9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRXMQBL128F427F1DB.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRBLLEI128F932948C.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRPXFZS128F4271CCB.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRYLZHF128F9304673.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRKLTLE128F9337985.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRTVEZZ128F14541C3.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRLTSIK128F428113A.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRTFBZU128F1452770.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRHZPUX128F42BC0F0.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRWMDUE128F14548DC.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRIYOLX128F426AA45.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRUMNUN128F145BB98.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRDDNSR12903D10460.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRWJAQQ128F9316359.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRZCMQL128F1455265.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQLXLM128F427CA0D.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRUHJZB128F9316344.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRLCONI128F4255EAC.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRAFYVC128F4268F8B.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRLBTZY128E0783309.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRXEIRM128EF346710.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRWHGDL128F92DDE4F.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRUCJPC128F145E31A.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRAULXY128F1452F8E.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRYOFAG128F931A4E5.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRWTAFB128F4243B58.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRANWNO128F425A572.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRSTDKJ128F92F8002.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRUSHBS128F426F02D.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TROMGYS128F930BCDB.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRGMDAQ128F933797D.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRTVIGE128F149B8FD.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TROJPWV128F9337986.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRANQIW128F4255EB5.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TROPJFT128F42732DE.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRPSNIP128F4255EAE.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQXDIJ12903CA4654.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRACVYB128F932A9DB.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRJWBFA128F149B8FB.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRGMNEE128F146AAD9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRNWWMH128F9316357.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRSLUXU128F4255EB4.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRMIQXY128F427CA14.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRXHOZL128F92D7A20.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRITCGV128F4290790.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRDIMBO128F1483658.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRWGEDC128F427EF4F.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRMLWKP128F92FC5DF.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRFBPLF128F4243CF9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRAVYPH128F149B902.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TREXRTM128F423EDD6.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TREGMNY128F9316353.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQQEWP128F426AA47.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRKTIWS128F4271D0B.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRKZZIS128F426F033.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRKVEGW128F428B618.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRIQOSH128F149B901.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRHQTZZ128F14933E9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRDJJIG128F1452772.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRPCMXL128F92E835E.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRBFDOH128F933797E.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TREWDCL12903CED47B.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRGKSSG128F9312489.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRGOJAX128F930F88A.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRZXSBW128F9351C97.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRJEETC128F92D1BF9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRWSTYN128F9331873.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQTSWL128F9307276.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TREFYAS128F92D7A12.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRRIGDV128F9304DEA.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRGTXZM128F933797F.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRCUTRZ128F1452776.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRJAKGL128F92FC3B5.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRMVJCE128F9316349.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQWUAH128EF346713.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRJYJBL128F9316351.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRAZGHD128F14541C4.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRJYMBD128F427EDDB.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRLNFFM128F4242EB2.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQACQT128F9316E5E.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRJMHKF128F14692F4.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRDXENJ128F1469FF9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRSRPHR128F9316355.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQFYWI128F92FBE63.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRQPOLL128E0792B70.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRYNDRC128F9316E5C.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRSIALT128F9337980.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRGJSYO128F1465644.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRVQGKW128F42293E9.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRIUVGX128F148C9F4.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRXUFKU128F14933E7.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRRGCXU128F14596E6.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRPYSXL128F149B8F8.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRRSGMK128F428B827.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRBRLWR12903CE2E34.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRCUQUJ128F92E1AA3.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRBJARK128F1465649.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRZFSGD128E0792BBA.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/World/World-TRBCSJN128F14541C2.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRUJLMG128E0781689.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRSPOSQ128F92D679E.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRYZVRM128F4268BC0.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRUMFSQ128F92D8942.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRFPEMC128F42928FE.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRGHZJJ128F426202D.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRYRSOF128F92F6BF2.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRYBRHJ128F145E2B5.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRXQERT128F42BAF3E.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRGLLXB128F92D5589.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRJWVNH12903D051C4.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRIGAXW128F423EE89.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRBPTYF128F423EEA3.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRFLLET12903CC3C86.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRFSFTT128F92F8CF3.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRLLIHJ128F425C76C.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRTNIGY128F148EF48.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TROABHR128F429596B.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRUCJTA128F14856CD.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRCRUXS128F92F1ED1.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRPVZZT128F423EEA5.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRFOQIV128F92EA111.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRUXWBF128E0785B09.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRDFICS128F930CB0C.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRQJEGR128F429554B.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRKQLRS128F4230F04.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRSRUWK128F426C900.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRUGYZP128F148EF4C.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRXIXSP128F42A04EC.mp3
/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1/MP3-Example/Folk/Folk-TRROABB128F428F0E8.mp3

In [7]:
users_data_path = list(data_path.rglob("*.csv"))[0]

df_users = pd.read_csv(users_data_path)
df_users.head()

             track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
3  TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
4  TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

In [8]:
df_songs = pd.read_csv(songs_data_path)
df_songs.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [9]:
df_songs.shape

(50683, 21)

In [11]:
df_songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50683 non-null  object
 1   name                 50683 non-null  object
 2   artist               50683 non-null  object
 3   spotify_preview_url  50683 non-null  object
 4   spotify_id           50683 non-null  object
 5   tags                 49556 non-null  object
 6   genre                22348 non-null  object
 7   year                 50683 non-null  int64
 8   duration_ms          50683 non-null  int64
 9   danceability         50683 non-null  float64
 10  energy               50683 non-null  float64
 11  key                  50683 non-null  int64
 12  loudness             50683 non-null  float64
 13  mode                 50683 non-null  int64
 14  speechiness          50683 non-null  float64
 15  acousticness         50683 non-null  float64
 16  instrumentalness     50683 non-null  float64
 17  liveness             50683 non-null  float64
 18  valence              50683 non-null  float64
 19  tempo                50683 non-null  float64
 20  time_signature       50683 non-null  int64
dtypes: float64(9), int64(5), object(7)
memory usage: 8.1+ MB

In [12]:
df_songs.isna().sum()

track_id                   0
name                       0
artist                     0
spotify_preview_url        0
spotify_id                 0
tags                    1127
genre                  28335
year                       0
duration_ms                0
danceability               0
energy                     0
key                        0
loudness                   0
mode                       0
speechiness                0
acousticness               0
instrumentalness           0
liveness                   0
valence                    0
tempo                      0
time_signature             0
dtype: int64